apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: project-39-dev-pipeline
  namespace: "project-39"
spec:
  pipelineRef:
    name: dev-pipeline
  params:
  - name: REVISION
    value: main
  - name: BUILD_COMMAND
    value: |
      go build -o manager main.go
  - name: TEST_IMAGE_NAME
    value: "harbor.bluzin.io/library/golang-test:1.1"
  - name: GOCACHE
    value: "/go/.cache"
  - name: CODE_REPO_URL
    value: "ssh://git@gitlab.bluzin.io:2222/nautes-labs/pkg.git"
  - name: SONAQUBE_HOST
    value: "http://10.204.118.216:32183"
  - name: SONAQUBE_KEY
    value: "pkg"
  - name: SONAQUBE_TOKEN
    value: "sqp_ea1b07b841625068d0b14272460d9e6e6176aca6"
  taskRunSpecs:
  - pipelineTaskName: git-clone
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/tls-secret: "ca"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: 'project-39'
        vault.hashicorp.com/agent-run-as-user: '0' 
        vault.hashicorp.com/agent-run-as-group: '0'
        vault.hashicorp.com/agent-inject-secret-id_ecdsa: "git/data/gitlab/project-39/default/rw"
        vault.hashicorp.com/secret-volume-path-id_ecdsa: "/root/.ssh"
        vault.hashicorp.com/agent-inject-perms-id_ecdsa: '0400'
        vault.hashicorp.com/agent-inject-template-id_ecdsa: |
          {{- with secret "git/data/gitlab/project-39/default/rw" -}}
          {{ .Data.data.deploykey }}
          {{- end -}}
  - pipelineTaskName: go-pull-dependency
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/tls-secret: "ca"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: 'project-39'
        vault.hashicorp.com/agent-run-as-user: '0' 
        vault.hashicorp.com/agent-run-as-group: '0'
        vault.hashicorp.com/agent-inject-secret-gitlab_ca.crt: "pki/data/default"
        vault.hashicorp.com/secret-volume-path-gitlab_ca.crt: "/usr/local/share/ca-certificates"
        vault.hashicorp.com/agent-inject-perms-gitlab_ca.crt: '0400'
        vault.hashicorp.com/agent-inject-template-gitlab_ca.crt: |
          {{- with secret "pki/data/default" -}}
          {{ .Data.data.cacert }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-id_ecdsa: "git/data/gitlab/project-39/default/rw"
        vault.hashicorp.com/secret-volume-path-id_ecdsa: "/root/.ssh"
        vault.hashicorp.com/agent-inject-perms-id_ecdsa: '0400'
        vault.hashicorp.com/agent-inject-template-id_ecdsa: |
          {{- with secret "git/data/gitlab/project-39/default/rw" -}}
          {{ .Data.data.deploykey }}
          {{- end -}}
  workspaces:
  - name: source-volume
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100M
  - name: go-path
    persistentVolumeClaim:
      claimName: go-tmp
  - name: sonar-settings
    emptyDir: {}